apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ArgoCD
  - BookingService
  - DashboardService
  - Gateway
  - GraphQL
  - InfrastructureService
  - MessageBroker
  - MovieService
  - ShowtimeService
  - UserService