apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-deployment
  namespace: graphql
  annotations:
    secrets.doppler.com/reload: 'true'
  labels:
    app: graphql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql
  template:
    metadata:
      name: graphql
      labels:
        app: graphql
    spec:
      containers:
        - name: graphql
          image: saltman0/cinephoria-graphql:1.0.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: GRAPHQL_URL
              valueFrom:
                secretKeyRef:
                  name: graphql-secret
                  key: GRAPHQL_URL
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: graphql-secret
                  key: PORT
      restartPolicy: Always
