apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gateway
resources:
  - HttpRoute-booking.yaml
  - HttpRoute-dashboard.yaml
  - HttpRoute-graphql.yaml
  - HttpRoute-infrastructure.yaml
  - HttpRoute-movie.yaml
  - HttpRoute-showtime.yaml
  - HttpRoute-user.yaml